---
apiVersion: v1
kind: Secret
metadata:
  name: database
  annotations:
    "helm.sh/hook": pre-install
data:
  user: {{ .Values.backendDatabase.user | b64enc | quote }}
  password: {{ .Values.backendDatabase.password | b64enc | quote }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  annotations:
    "helm.sh/hook": pre-install
data:
  username: {{ .Values.backendState.username | b64enc | quote }}
  password: {{ .Values.backendState.password | b64enc | quote }}
type: Opaque
