{{- range .Values.secretsExtra }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}"
  annotations:
    "helm.sh/hook": pre-install
data:
{{- range $key, $val := .value }}
  {{ $key }}: {{ $val | b64enc | nindent 4 }}
{{- end }}
type: Opaque
{{- end }}
