routingRules:
  rulesEngineEnabled: {{ default .Env.ROUTING_RULES_ENABLED "false" }}
  # rulesConfigPath: "src/main/resources/rules/routing_rules.yml"

requestRouter:
  port: {{ default .Env.REQUEST_ROUTER_PORT "8080" }}
  name: trinoRouter
  historySize: {{ default .Env.QUERY_HISTORY_SIZE "1000" }}
  requestBufferSize: 8192

dataStore:
  jdbcUrl: {{ default .Env.JDBC_URL "" }}
  user: {{ default .Env.DB_USER "" }}
  password: {{ default .Env.DB_PASSWORD "" }}
  driver: {{ default .Env.JDBC_DRIVER "" }}
  queryHistoryHoursRetention: 24

backendState:
  username: {{ default .Env.BACKEND_STATE_USERNAME "lb_query" }}
  password: {{ default .Env.BACKEND_STATE_PASSWORD "" }}
  ssl: {{ default .Env.BACKEND_STATE_SSL "true" }}

clusterStatsConfiguration:
  useApi: true

server:
  applicationConnectors:
    - type: http
      port: {{ default .Env.APPLICATION_CONNECTOR_PORT "8090" }}
      useForwardedHeaders: true
  adminConnectors:
    - type: http
      port: {{ default .Env.ADMIN_CONNECTOR_PORT "8091" }}
      useForwardedHeaders: true

modules:
  - io.trino.gateway.ha.module.HaGatewayProviderModule
  - io.trino.gateway.ha.module.ClusterStateListenerModule
  - io.trino.gateway.ha.module.ClusterStatsMonitorModule

managedApps:
  - io.trino.gateway.ha.GatewayManagedApp
  - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: {{ default .Env.LOG_LEVEL "INFO" }}

  # Logger-specific levels.
  loggers:
    io.trino: {{ default .Env.LOG_LEVEL_LOGGERS "INFO" }}

  appenders:
    - type: console
      filterFactories:
        - type: Log-filter-factory

extraWhitelistPaths:
  - "/ui/insights"
  - "/api/v1/biac"
  - "/api/v1/dataProduct"
  - "/api/v1/dataproduct"
  - "/ext/faster"
